id: PB75CE6E6
initial_creation_type: input
source_metadata:
  title: Ten Royal Sūtras
  language: fr
  description: 'A collection related to the ten royal sūtras or ten sūtras of the
    king (rgyal po''i mdo bcu), which are said to have been translated upon the advice
    of Padmasambhava for Emperor Tri Songdetsen''s daily recitation:'
  volume:
    fb12423a6a214c2aad3ea3fd76300cd0:
      title: Outline of the Ten Royal Sūtras
      parent: Outlines
    cdd618f5739747fdb630b0a41fdbd2bf:
      title: The Bodhisattva’s Confession of Downfalls (Nyingma Version)
      parent: Sūtras
    a6535a1cf6de4fd5b24aaf277f22f9b2:
      title: The Dhāraṇī of Stream of Wealth (Vasudhārā)
      parent: Sūtras
    5a715ebe61e24448a062dccfc9b3c8ba:
      title: The Heart of the Transcendent Perfection of Wisdom
      parent: Sūtras
    5181a257abdc4126a42ef2db962a6bb4:
      title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good
        Actions” (Zangchö Mönlam)'
      parent: Sūtras
    048d79f04ab84cb7a3b47375dfb90b97:
      title: The Noble Dhāraṇī of The Supreme Accomplishment of Sitātapatrā Born from
        the Tathāgata’s Uṣṇīṣa, the Great Invincible Dispeller
      parent: Sūtras
    a303a10c5f6442fcab9fd826d3e92bcb:
      title: The Noble Incantation entitled ‘The Rituals for the Blue-Clad Vajrapāṇi’
      parent: Sūtras
    35049cb71bc042fd8beb8c9d128ea9df:
      title: The Noble Mahāyāna Sūtra entitled The Wisdom of the Hour of Death
      parent: Sūtras
    6457c776e9d74f7388e2f526344a539f:
      title: The Perfection of Wisdom, Mother of All Tathāgatas, ‘In One Syllable’
      parent: Sūtras
    b7972d33ab4f4dd8bac88256b28a71a6:
      title: The Sūtra of Boundless Life and Wisdom
      parent: Sūtras
    5eedc37989b649e4972b2f1602031aff:
      title: Vajravidāraṇa Dhāraṇī (Nyingma Version)
      parent: Sūtras
created_at: '2022-03-01T06:06:38.013453'
last_modified_at: '2022-03-01T06:06:38.013455'
